<ul class="menu-area-main">
                                 <li class="active"><a href="#home">Home</a></li>
                                 <li><a href="#about">About</a></li>
                                 <li><a href="#products">products</a></li>
                                 <li><a href="#gallery">gallery</a></li>
                                 <li><a href="#contact">Contact Us</a></li>
                              </ul>